export const mockRepositories = [
  {
    id: 142, name: 'OpenSourceAI', fullName: 'owner/OpenSourceAI', owner: 'owner',
    description: 'AI-powered developer productivity platform that makes thoughtful tooling accessible to every team.',
    url: 'https://github.com/owner/OpenSourceAI', stars: 12400, forks: 1800, language: 'JavaScript',
    topics: ['react', 'ai', 'developer-tools'], goodFirstIssueCount: 8, matchScore: 94,
    whyMatch: ['Your React and JavaScript skills match the project stack.', 'The AI focus aligns with your interests.', 'Beginner-friendly issues are available for your experience level.'],
    recommendedIssue: {
      title: 'Improve mobile navigation', number: 142, url: 'https://github.com/owner/OpenSourceAI/issues/142',
      difficulty: 'Beginner', skills: ['React', 'JavaScript'],
      explanation: 'Make the navigation easier to use on smaller screens by improving its responsive menu behavior.',
    },
  },
  {
    id: 2, name: 'Patchwork', fullName: 'patchwork-dev/patchwork', owner: 'patchwork-dev',
    description: 'A welcoming toolkit for turning small, focused fixes into lasting open-source habits.',
    url: 'https://github.com/patchwork-dev/patchwork', stars: 6800, forks: 740, language: 'TypeScript',
    topics: ['open-source', 'community', 'developer-tools'], goodFirstIssueCount: 14, matchScore: 89,
    whyMatch: ['Your web development interests fit the product.', 'The contribution workflow is designed for first-time contributors.'],
    recommendedIssue: { title: 'Add keyboard shortcuts to the issue filters', number: 86, url: 'https://github.com/patchwork-dev/patchwork/issues/86', difficulty: 'Beginner', skills: ['React', 'JavaScript'] },
  },
  {
    id: 3, name: 'Model Garden', fullName: 'garden-labs/model-garden', owner: 'garden-labs',
    description: 'Explore practical, community-built examples for bringing machine learning into everyday apps.',
    url: 'https://github.com/garden-labs/model-garden', stars: 9100, forks: 1200, language: 'Python',
    topics: ['machine-learning', 'ai', 'examples'], goodFirstIssueCount: 6, matchScore: 86,
    whyMatch: ['Your AI interests align with the project examples.', 'Its documentation and sample apps offer approachable ways to contribute.'],
    recommendedIssue: { title: 'Document the local quickstart for embeddings', number: 203, url: 'https://github.com/garden-labs/model-garden/issues/203', difficulty: 'Beginner', skills: ['Python', 'Documentation'] },
  },
  {
    id: 4, name: 'Tinybench', fullName: 'tinybenchjs/tinybench', owner: 'tinybenchjs',
    description: 'A lightweight benchmarking library that helps JavaScript developers make faster code with confidence.',
    url: 'https://github.com/tinybenchjs/tinybench', stars: 5200, forks: 310, language: 'JavaScript',
    topics: ['javascript', 'performance', 'testing'], goodFirstIssueCount: 3, matchScore: 82,
    whyMatch: ['JavaScript is central to the codebase.', 'The small, focused package makes it easy to learn the contribution workflow.'],
    recommendedIssue: { title: 'Add an example for comparing async tasks', number: 59, url: 'https://github.com/tinybenchjs/tinybench/issues/59', difficulty: 'Intermediate', skills: ['JavaScript', 'Node.js'] },
  },
  {
    id: 5, name: 'Good First PR', fullName: 'good-first-pr/community', owner: 'good-first-pr',
    description: 'A community-curated map of friendly projects, clear contribution guides, and maintainers who say hello.',
    url: 'https://github.com/good-first-pr/community', stars: 3400, forks: 520, language: 'JavaScript',
    topics: ['open-source', 'community', 'good-first-issue'], goodFirstIssueCount: 21, matchScore: 79,
    whyMatch: ['Your interest in open source fits the community mission.', 'There are many documented entry points for new contributors.'],
    recommendedIssue: { title: 'Refresh the contributor welcome page', number: 117, url: 'https://github.com/good-first-pr/community/issues/117', difficulty: 'Beginner', skills: ['JavaScript', 'Documentation'] },
  },
]